// Generated by Fantasticon from the numbered SVG sources in ../svg.
// Do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart' show IconData;

/// Coffee-related icons designed for use with Flutter's `Icon` widget.
///
/// Snake_case names are retained for compatibility with the original Coffeico
/// API. The numeric SVG filename prefixes define the stable codepoints.
class Coffeico {
  static const _fontFamily = 'Coffeico';
  static const _fontPackage = 'coffeico_plus';

  /// The `aeropress` icon.
  static const IconData aeropress = IconData(
    0xf101,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `chemex` icon.
  static const IconData chemex = IconData(
    0xf102,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `clever_dripper` icon.
  static const IconData clever_dripper = IconData(
    0xf103,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `french_press` icon.
  static const IconData french_press = IconData(
    0xf104,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `hario_v60` icon.
  static const IconData hario_v60 = IconData(
    0xf105,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `kalita_wave` icon.
  static const IconData kalita_wave = IconData(
    0xf106,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `origami` icon.
  static const IconData origami = IconData(
    0xf107,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `wilfa_svart` icon.
  static const IconData wilfa_svart = IconData(
    0xf108,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `bean` icon.
  static const IconData bean = IconData(
    0xf109,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `coffee_maker` icon.
  static const IconData coffee_maker = IconData(
    0xf10a,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `portafilter` icon.
  static const IconData portafilter = IconData(
    0xf10b,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `bag` icon.
  static const IconData bag = IconData(
    0xf10c,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `bag_with_bean` icon.
  static const IconData bag_with_bean = IconData(
    0xf10d,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `hario_switch` icon.
  static const IconData hario_switch = IconData(
    0xf10e,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `melita_cone` icon.
  static const IconData melita_cone = IconData(
    0xf10f,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `bee_house_dripper` icon.
  static const IconData bee_house_dripper = IconData(
    0xf110,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `phin_filter` icon.
  static const IconData phin_filter = IconData(
    0xf111,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `neapolitan_flip_pot` icon.
  static const IconData neapolitan_flip_pot = IconData(
    0xf112,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `moka_pot` icon.
  static const IconData moka_pot = IconData(
    0xf113,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `siphon_brewer` icon.
  static const IconData siphon_brewer = IconData(
    0xf114,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `cezve` icon.
  static const IconData cezve = IconData(
    0xf115,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `tricolate` icon.
  static const IconData tricolate = IconData(
    0xf116,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `pulsar` icon.
  static const IconData pulsar = IconData(
    0xf117,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `ufo_dripper` icon.
  static const IconData ufo_dripper = IconData(
    0xf118,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `orea_brewer` icon.
  static const IconData orea_brewer = IconData(
    0xf119,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `april_brewer` icon.
  static const IconData april_brewer = IconData(
    0xf11a,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `ceado_hoop_brewer` icon.
  static const IconData ceado_hoop_brewer = IconData(
    0xf11b,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `oxo_rapid_brewer` icon.
  static const IconData oxo_rapid_brewer = IconData(
    0xf11c,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `timermore_b75` icon.
  static const IconData timermore_b75 = IconData(
    0xf11d,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `espro_bloom` icon.
  static const IconData espro_bloom = IconData(
    0xf11e,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `menu` icon.
  static const IconData menu = IconData(
    0xf11f,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `weber_workshops_bird` icon.
  static const IconData weber_workshops_bird = IconData(
    0xf120,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `cafec_flower` icon.
  static const IconData cafec_flower = IconData(
    0xf121,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );

  /// The `cupping_bowl` icon.
  static const IconData cupping_bowl = IconData(
    0xf122,
    fontFamily: _fontFamily,
    fontPackage: _fontPackage,
  );
}
